[package]
name = "take5"
version = "0.2.0"
authors = [
    "Nathan Lilienthal <nathan@nixpulvis.com>",
    "Alex Jo <jo.al@husky.neu.edu>",
]

[dependencies]
itertools = "0.4"
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
